version: "2"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "rrp"
      MYSQL_PASS: "rrp"
    volumes:
      - rrp-volume:/var/lib/mysql
volumes:
  rrp-volume:
