version: "3.8" # It's good practice to use a newer version if possible
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "rrp"
      MYSQL_PASSWORD: "rrp"
      # This environment variable forces mysql to use the native password auth:
      MYSQL_ROOT_HOST: "%" # Allows root access from any host
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - rrp-volume:/var/lib/mysql
volumes:
  rrp-volume:
